Hackaton/Hackaton/Controllers/AdvertisementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Hackaton.Data;
using Hackaton.Models.Advertisement;
using Microsoft.AspNetCore.Authorization;

public class AdvertisementController : Controller
{
    private readonly ApplicationDbContext _context;

    public AdvertisementController(ApplicationDbContext context)
    {
        _context = context;
    }

    [AllowAnonymous]
    [HttpGet]
    public IActionResult Index()
    {
        var advertisements = _context.AdvertisementData.ToList();
        return View(advertisements);
    }

    [AllowAnonymous]
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(AdvertisementData model)
    {
        if (ModelState.IsValid)
        {
            _context.AdvertisementData.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(model);
    }

    [AllowAnonymous]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var advertisement = await _context.AdvertisementData.FindAsync(id);
        if (advertisement != null)
        {
            _context.AdvertisementData.Remove(advertisement);
            await _context.SaveChangesAsync();
        }
        return RedirectToAction("Index");
    }


    private bool AdvertisementExists(int id)
    {
        return _context.AdvertisementData.Any(e => e.Id == id);
    }

    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var advertisement = await _context.AdvertisementData.FindAsync(id);
        if (advertisement == null)
        {
            return NotFound();
        }
        return View(advertisement);
    }

    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var advertisement = await _context.AdvertisementData.FindAsync(id);
        if (advertisement == null)
        {
            return NotFound();
        }
        return View(advertisement);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, AdvertisementData model)
    {
        if (id != model.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AdvertisementExists(model.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }
        return View(model);
    }
}

Hackaton/Hackaton/Controllers/UserController.cs
using Hackaton.Models;
using Hackaton.Models.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Hackaton.Validation.User;
using Hackaton.Data;
using Hackaton.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using MySqlX.XDevAPI.Common;


namespace Hackaton.Controllers
{
    public class UserController : Controller
    {
        public readonly ILogger<UserController> _logger;
        public readonly IApplicationDbContext _db;
        public readonly IUserService _userService;
        private readonly UserSignUpValidator _signUpValidator;
        private readonly UserLoginValidator _logInValidator;

        private readonly UserManager<UserData> _userManager;

        public UserController(ILogger<UserController> logger, IUserService userService, IApplicationDbContext db, UserSignUpValidator signUpValidator, UserLoginValidator logInValidator, UserManager<UserData> userManager)
        {
            _logger = logger;
            _userService = userService;
            _db = db;
            _signUpValidator = signUpValidator;
            _logInValidator = logInValidator;

            _userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult SignUp()
        {
            var user = HttpContext.User.Identity.IsAuthenticated;
            if (user == true)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Chat()
        {
            var user = HttpContext.User.Identity.IsAuthenticated;
            if (user == true)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(UserData model)
        {
            var validationResult = _signUpValidator.Validate(model);

            _logger.LogInformation($"validationResult {validationResult}");
            if (validationResult.IsValid)
            {
                var userExists = await _userManager.FindByEmailAsync(model.Email);
                if (userExists != null)
                {
                    _logger.LogInformation("Email already exists! Try LogIn or use another email!");
                    return StatusCode(StatusCodes.Status500InternalServerError);
                }

                model.UserName = model.Email;

                var result = await _userManager.CreateAsync(model, model.Password);
                if (!result.Succeeded)
                {
                    _logger.LogInformation($"!result.Succeeded {result.ToString()}");
                    return StatusCode(StatusCodes.Status500InternalServerError);
                }
                _logger.LogInformation("result.Succeeded");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(model);
            }
        }
        
        [AllowAnonymous]
        [HttpGet]
        public IActionResult LogIn()
        {
            var user = HttpContext.User.Identity.IsAuthenticated;
            if (user == true)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn(LogInData model)
        {
            var validationResult = _logInValidator.Validate(model);

            if (validationResult.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                if (user == null)
                {
                    _logger.LogInformation("No such user! (LogIn User)");
                    return Unauthorized();
                }
                var is_valid_password = await _userManager.CheckPasswordAsync(user, model.Password);
                if (!is_valid_password)
                {
                    _logger.LogInformation("Wrong password! (LogIn User)");
                    return Unauthorized();
                }

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Email, model.Email)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                _logger.LogInformation("Success Login! (LogIn User)");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(model);
            }
        }

        [HttpGet]
        [HttpPost]
        [Route("/User/Logout")]
        public async Task<IActionResult> LogOut()
        {
            _logger.LogInformation($"Logout!");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hackaton/Hackaton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hackaton</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hackaton.styles.css" asp-append-version="true" />
</head>
<body>
    <script>
        let x = document.cookie;
        console.log(x);
        // var role = document.querySelector('#role');

        // if (role.getAttribute('value') == 'Edit') {
        //     role.style.display = 'none';
        // }
    </script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hackaton</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("LogIn", "User")" class="btn btn-primary">LogIn</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("SignUp", "User")" class="btn btn-primary">SignUp</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("LogOut", "User")" class="btn btn-primary">LogOut</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Create", "Advertisement")" class="btn btn-primary">Add advertisement </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Advertisement")" class="btn btn-primary">Advertisement </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>